spring:
  datasource:
    username: postgres
    password: smndr2013
    url: jdbc:postgresql://localhost:5432/ecommerce
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  data:
    rest:
      base-path: /api
  h2:
    console:
      path: /h2
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /
jwt:
  secret: hellowoldsdfsdfdsfgadszo3e48973w@@@^%$^%$%^kjdfhskjlfhskj
  expire-date: 8640000
springdoc:
  swagger-ui:
    path: /doc
    operationsSorter: method
  api-docs:
    path: /api-docs
