spring:
  datasource:
    username: postgres
    password: smndr2013
    url: jdbc:postgresql://localhost:5432/ecommerce
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  data:
    rest:
      base-path: /api

server:
  port: 8080
jwt:
  secret: jwtsecretkey
  expire-date: 8640000
